# Generated by Django 5.2.7 on 2025-10-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_achievement_dailyquest_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='learning_language',
            field=models.CharField(blank=True, choices=[('es', 'Spanish'), ('zh', 'Chinese'), ('fr', 'French')], max_length=2, null=True),
        ),
    ]
