# Generated by Django 5.2.7 on 2025-10-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userprofile_learning_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_heart_restore',
            field=models.DateTimeField(blank=True, help_text='Last time hearts were restored to maximum', null=True),
        ),
    ]
