# Generated by Django 5.2.7 on 2025-10-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_last_heart_restore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('TR', 'Translate'), ('MP', 'Match Pairs'), ('LS', 'Listen'), ('SP', 'Speak'), ('LC', 'Listen & Construct')], default='TR', max_length=2),
        ),
    ]
