# Generated by Django 5.2.7 on 2025-11-13 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hearts',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
