# Generated by Django 5.2.7 on 2025-11-15 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userprofile_hearts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdailyquest',
            unique_together={('user', 'quest', 'date_assigned')},
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='is_weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdailyquest',
            name='week_assigned',
            field=models.IntegerField(blank=True, help_text='Week number of the year for weekly quests', null=True),
        ),
        migrations.AddField(
            model_name='userdailyquest',
            name='year_assigned',
            field=models.IntegerField(blank=True, help_text='Year for weekly quests', null=True),
        ),
        migrations.AlterField(
            model_name='dailyquest',
            name='quest_type',
            field=models.CharField(choices=[('earn_xp', 'Earn XP'), ('complete_lessons', 'Complete Lessons'), ('perfect_lesson', 'Get a Perfect Lesson'), ('use_no_hearts', 'Complete without losing hearts'), ('weekly_warrior', 'Weekly Warrior'), ('streak_master', 'Streak Master')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='userdailyquest',
            unique_together={('user', 'quest', 'date_assigned'), ('user', 'quest', 'week_assigned', 'year_assigned')},
        ),
    ]
